Traceback (most recent call last):
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\blocks.py", line 1768, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\components\gallery.py", line 238, in postprocess
    for o in executor.map(_save, value):
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
    return self.__get_result()
    return self.__get_result()
    return self.__get_result()
    return self.__get_result()
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\concurrent\futures\_base.py", line 391, in __get_result
    return self.__get_result()
    return self.__get_result()
    return self.__get_result()
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\siyiliu2\.conda\envs\cnn\lib\site-packages\gradio\components\gallery.py", line 204, in _save
    img, caption = img
ValueError: not enough values to unpack (expected 2, got 0)
